using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace deobfuscator {
    internal class FlareObfu2 {
        public Dictionary<uint, OT> dictionary;

        public FlareObfu2() {
            dictionary = new Dictionary<uint, OT> {
                { 88U, OT.A },
                { 214U, OT.A },
                { 215U, OT.A },
                { 95U, OT.A },
                { 65024U, OT.A },
                { 59U, OT.D },
                { 46U, OT.C },
                { 60U, OT.D },
                { 47U, OT.C },
                { 65U, OT.D },
                { 52U, OT.C },
                { 61U, OT.D },
                { 48U, OT.C },
                { 66U, OT.D },
                { 53U, OT.C },
                { 62U, OT.D },
                { 49U, OT.C },
                { 67U, OT.D },
                { 54U, OT.C },
                { 63U, OT.D },
                { 50U, OT.C },
                { 68U, OT.D },
                { 55U, OT.C },
                { 64U, OT.D },
                { 51U, OT.C },
                { 140U, OT.B },
                { 56U, OT.D },
                { 43U, OT.C },
                { 1U, OT.A },
                { 57U, OT.D },
                { 44U, OT.C },
                { 58U, OT.D },
                { 45U, OT.C },
                { 40U, OT.B },
                { 41U, OT.B },
                { 111U, OT.B },
                { 116U, OT.B },
                { 65025U, OT.A },
                { 65026U, OT.A },
                { 65027U, OT.A },
                { 195U, OT.A },
                { 65028U, OT.A },
                { 65029U, OT.A },
                { 65046U, OT.B },
                { 211U, OT.A },
                { 103U, OT.A },
                { 104U, OT.A },
                { 105U, OT.A },
                { 106U, OT.A },
                { 212U, OT.A },
                { 138U, OT.A },
                { 179U, OT.A },
                { 130U, OT.A },
                { 181U, OT.A },
                { 131U, OT.A },
                { 183U, OT.A },
                { 132U, OT.A },
                { 185U, OT.A },
                { 133U, OT.A },
                { 213U, OT.A },
                { 139U, OT.A },
                { 180U, OT.A },
                { 134U, OT.A },
                { 182U, OT.A },
                { 135U, OT.A },
                { 184U, OT.A },
                { 136U, OT.A },
                { 186U, OT.A },
                { 137U, OT.A },
                { 118U, OT.A },
                { 107U, OT.A },
                { 108U, OT.A },
                { 224U, OT.A },
                { 210U, OT.A },
                { 209U, OT.A },
                { 109U, OT.A },
                { 110U, OT.A },
                { 65047U, OT.A },
                { 112U, OT.B },
                { 91U, OT.A },
                { 92U, OT.A },
                { 37U, OT.A },
                { 65041U, OT.A },
                { 220U, OT.A },
                { 65048U, OT.A },
                { 65045U, OT.B },
                { 117U, OT.B },
                { 39U, OT.B },
                { 65033U, OT.F },
                { 2U, OT.A },
                { 3U, OT.A },
                { 4U, OT.A },
                { 5U, OT.A },
                { 14U, OT.E },
                { 65034U, OT.F },
                { 15U, OT.E },
                { 32U, OT.G },
                { 22U, OT.A },
                { 23U, OT.A },
                { 24U, OT.A },
                { 25U, OT.A },
                { 26U, OT.A },
                { 27U, OT.A },
                { 28U, OT.A },
                { 29U, OT.A },
                { 30U, OT.A },
                { 21U, OT.A },
                { 31U, OT.E },
                { 33U, OT.H },
                { 34U, OT.G },
                { 35U, OT.H },
                { 163U, OT.B },
                { 151U, OT.A },
                { 144U, OT.A },
                { 146U, OT.A },
                { 148U, OT.A },
                { 150U, OT.A },
                { 152U, OT.A },
                { 153U, OT.A },
                { 154U, OT.A },
                { 145U, OT.A },
                { 147U, OT.A },
                { 149U, OT.A },
                { 143U, OT.B },
                { 123U, OT.B },
                { 124U, OT.B },
                { 65030U, OT.B },
                { 77U, OT.A },
                { 70U, OT.A },
                { 72U, OT.A },
                { 74U, OT.A },
                { 76U, OT.A },
                { 78U, OT.A },
                { 79U, OT.A },
                { 80U, OT.A },
                { 71U, OT.A },
                { 73U, OT.A },
                { 75U, OT.A },
                { 142U, OT.A },
                { 65036U, OT.F },
                { 6U, OT.A },
                { 7U, OT.A },
                { 8U, OT.A },
                { 9U, OT.A },
                { 17U, OT.E },
                { 65037U, OT.F },
                { 18U, OT.E },
                { 20U, OT.A },
                { 113U, OT.B },
                { 126U, OT.B },
                { 127U, OT.B },
                { 114U, OT.B },
                { 208U, OT.B },
                { 65031U, OT.B },
                { 221U, OT.D },
                { 222U, OT.C },
                { 65039U, OT.A },
                { 198U, OT.B },
                { 90U, OT.A },
                { 216U, OT.A },
                { 217U, OT.A },
                { 101U, OT.A },
                { 141U, OT.B },
                { 115U, OT.B },
                { 65049U, OT.E },
                { 0U, OT.A },
                { 102U, OT.A },
                { 96U, OT.A },
                { 38U, OT.A },
                { 254U, OT.A },
                { 253U, OT.A },
                { 252U, OT.A },
                { 251U, OT.A },
                { 250U, OT.A },
                { 249U, OT.A },
                { 248U, OT.A },
                { 255U, OT.A },
                { 65054U, OT.A },
                { 65053U, OT.A },
                { 194U, OT.B },
                { 93U, OT.A },
                { 94U, OT.A },
                { 42U, OT.A },
                { 65050U, OT.A },
                { 98U, OT.A },
                { 99U, OT.A },
                { 100U, OT.A },
                { 65052U, OT.B },
                { 65035U, OT.F },
                { 16U, OT.E },
                { 164U, OT.B },
                { 155U, OT.A },
                { 156U, OT.A },
                { 157U, OT.A },
                { 158U, OT.A },
                { 159U, OT.A },
                { 160U, OT.A },
                { 161U, OT.A },
                { 162U, OT.A },
                { 125U, OT.B },
                { 223U, OT.A },
                { 82U, OT.A },
                { 83U, OT.A },
                { 84U, OT.A },
                { 85U, OT.A },
                { 86U, OT.A },
                { 87U, OT.A },
                { 81U, OT.A },
                { 65038U, OT.F },
                { 10U, OT.A },
                { 11U, OT.A },
                { 12U, OT.A },
                { 13U, OT.A },
                { 19U, OT.E },
                { 129U, OT.B },
                { 128U, OT.B },
                { 89U, OT.A },
                { 218U, OT.A },
                { 219U, OT.A },
                { 69U, OT.I },
                { 65044U, OT.A },
                { 122U, OT.A },
                { 65042U, OT.E },
                { 121U, OT.B },
                { 165U, OT.B },
                { 65043U, OT.A },
                { 97U, OT.A }
            };
        }
    }

    public enum OT {
        // Token: 0x0400003C RID: 60
        A,
        // Token: 0x0400003D RID: 61
        B,
        // Token: 0x0400003E RID: 62
        C,
        // Token: 0x0400003F RID: 63
        D,
        // Token: 0x04000040 RID: 64
        E,
        // Token: 0x04000041 RID: 65
        F,
        // Token: 0x04000042 RID: 66
        G,
        // Token: 0x04000043 RID: 67
        H,
        // Token: 0x04000044 RID: 68
        I
    }
}
